// Code generated by hertz generator.

package order

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _confirmorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _order0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryordersMw() []app.HandlerFunc {
	// your code...
	return nil
}
