// Code generated by hertz generator.

package appointment

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryappointmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateappointmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delappointmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appointmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createappointmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _confirmstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}
