// Code generated by hertz generator.

package membership

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _membershipMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _membershiploginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _membershipregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatememberreqMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepointMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querymemMw() []app.HandlerFunc {
	// your code...
	return nil
}
