// Code generated by hertz generator.

package membership

import (
	"context"

	membership "github.com/Gorsonpy/catCafe/biz/model/membership"
	"github.com/Gorsonpy/catCafe/biz/pack"
	"github.com/Gorsonpy/catCafe/biz/service"
	"github.com/Gorsonpy/catCafe/pkg/errno"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// MembershipLogin .
// @router /membership/login [POST]
func MembershipLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req membership.LoginRegisterReq
	resp := new(membership.LoginResponse)
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.PackLoginResp(resp, errno.ParamError.ErrorCode, errno.ParamError.ErrorMsg, "")
		c.JSON(consts.StatusOK, resp)
		return
	}

	code, msg, token := service.MembershipLogin(req.Username, req.Passwd)
	pack.PackLoginResp(resp, code, msg, token)
	c.JSON(consts.StatusOK, resp)
}

// MembershipRegister .
// @router /membership/register [POST]
func MembershipRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req membership.LoginRegisterReq
	resp := new(membership.BaseResponse)
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.PackBase(resp, errno.ParamError.ErrorCode, errno.ParamError.ErrorMsg)
		c.JSON(consts.StatusOK, resp)
		return
	}
	code, msg := service.MembershipRegister(req.Username, req.Passwd)
	pack.PackBase(resp, code, msg)
	c.JSON(consts.StatusOK, resp)
}
