// Code generated by hertz generator.

package cat

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatecatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querycatsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addcatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delcatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _catMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querycatsbypopMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadfileMw() []app.HandlerFunc {
	// your code...
	return nil
}
