// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	appointment "github.com/Gorsonpy/catCafe/biz/router/appointment"
	cat "github.com/Gorsonpy/catCafe/biz/router/cat"
	membership "github.com/Gorsonpy/catCafe/biz/router/membership"
	order "github.com/Gorsonpy/catCafe/biz/router/order"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	order.Register(r)

	appointment.Register(r)

	cat.Register(r)

	membership.Register(r)

}
